### ISSUE TITLE
Measurement.to_hdf5 doesn't save in_sig data

### ISSUE THREAD

**Issue by odoare** [odoare/measpy#83]
@csavaro : saving in_sig data in Measurement.to_hdf5 seems to fail. Commenting out l278-302 fixes the problem. What is the purpose of these lines ?

**Comment by csavaro** [comment]
These line are suposed to define the method used to write directly the data from device, with all channels in the same dataset.
The condition that there is no data in the Signal is missing.
Change l 278 with 
`elif (Nchannel := len(mesu["in_map"])) > 1 and mesu["in_sig"][0].dur == 0:`
